services:
  blob-azr.blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    container_name: azr.blob-storage
    volumes:
      - ./containers/blob_storage/data:/data
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"