services:
  blob-azr.blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    container_name: azr.blob-storage
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./containers/blob_storage/data:/data
    restart: always
    command: 'azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001'
    networks:
      - monitoring

  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - monitoring

  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - prometheus
      - blob-azr.blob-storage
    networks:
      - monitoring

  k6:
    image: loadimpact/k6
    container_name: k6
    ports:
      - '6565:6565'
    volumes:
      - ./k6-test.js:/test.js
    environment:
      - K6_NO_USAGE_REPORT
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
