services:
  blob-azr.blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    container_name: azr.blob-storage
    networks:
      - bridge
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./containers/blob_storage/data:/data
    restart: always
    command: 'azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001'

networks:
  bridge:
    driver: bridge
