spring:
  cloud:
    azure:
      storage:
        connection-string: "UseDevelopmentStorage=true"
        containerName: azr.blob-storage
        client:
          logging:
            level: BODY_AND_HEADERS
