spring:
  cloud:
    azure:
      storage:
        connection-string: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;"
        container-name: test1
        client:
          logging:
            level: BODY_AND_HEADERS
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mvc:
      view:
        prefix: /templates/
        suffix: .html
    web:
      resources:
        static-locations: classpath:/static/
    servlet:
      multipart:
        enabled: true
        max-file-size: -1 # Adjust this as needed
        max-request-size: -1  # Adjust this as needed
        fileSizeThreshold: -1
    server:
      port: 8080
      tomcat:
        max-post-size: -1
        max-swallow-size: -1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.springframework.web: DEBUG
